"""
Reports router — HR only.

Endpoints:
  GET /reports/export/excel  — stream full candidate list as .xlsx
  GET /reports/export/pdf    — stream funnel summary report as PDF
"""

import io
import logging
from datetime import datetime
from typing import Any, Dict, List

from fastapi import APIRouter, Depends
from fastapi.responses import StreamingResponse
from sqlalchemy import func
from sqlalchemy.orm import Session

from app.database import get_db
from app.dependencies import require_hr_role
from app.models.candidate import Candidate, CandidateStatus
from app.models.joining import JoiningRecord, JoiningStatus
from app.models.user import User

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/reports", tags=["reports"], redirect_slashes=False)

FUNNEL_ORDER = [
    CandidateStatus.new_application.value,
    CandidateStatus.shortlisted.value,
    CandidateStatus.interview_scheduled.value,
    CandidateStatus.selected.value,
    CandidateStatus.rejected.value,
    CandidateStatus.hold.value,
    "Joined",
]


def _get_funnel_totals(db: Session) -> Dict[str, int]:
    status_rows = (
        db.query(Candidate.status, func.count(Candidate.id))
        .group_by(Candidate.status)
        .all()
    )
    totals: Dict[str, int] = {s: 0 for s in FUNNEL_ORDER}
    for status_val, cnt in status_rows:
        if status_val in totals:
            totals[status_val] = cnt
    totals["Joined"] = (
        db.query(func.count(JoiningRecord.id))
        .filter(JoiningRecord.status == JoiningStatus.joined.value)
        .scalar()
        or 0
    )
    return totals


# ---------------------------------------------------------------------------
# GET /reports/export/excel
# ---------------------------------------------------------------------------

@router.get(
    "/export/excel",
    summary="Export candidate list to Excel (HR only)",
    response_class=StreamingResponse,
)
def export_excel(
    db: Session = Depends(get_db),
    _: User = Depends(require_hr_role),
) -> StreamingResponse:
    import openpyxl
    from openpyxl.styles import Alignment, Font, PatternFill, Border, Side

    candidates = (
        db.query(Candidate).order_by(Candidate.created_at.desc()).all()
    )

    wb = openpyxl.Workbook()
    ws = wb.active
    ws.title = "Candidates"

    # ── Header styling ───────────────────────────────────────────────────────
    header_font = Font(name="Calibri", bold=True, color="FFFFFF", size=11)
    header_fill = PatternFill(start_color="0F2040", end_color="0F2040", fill_type="solid")
    header_align = Alignment(horizontal="center", vertical="center", wrap_text=True)
    thin = Side(style="thin", color="CCCCCC")
    border = Border(left=thin, right=thin, top=thin, bottom=thin)

    headers = [
        "Application ID",
        "Full Name",
        "Department",
        "Status",
        "Qualification",
        "Experience (yrs)",
        "Expected CTC (₹)",
        "Date Applied",
    ]
    col_widths = [18, 24, 20, 20, 20, 16, 16, 16]

    ws.row_dimensions[1].height = 30
    for col_idx, (header, width) in enumerate(zip(headers, col_widths), start=1):
        cell = ws.cell(row=1, column=col_idx, value=header)
        cell.font = header_font
        cell.fill = header_fill
        cell.alignment = header_align
        cell.border = border
        ws.column_dimensions[cell.column_letter].width = width

    # ── Data rows ────────────────────────────────────────────────────────────
    alt_fill = PatternFill(start_color="EAF1FB", end_color="EAF1FB", fill_type="solid")
    data_align = Alignment(vertical="center")

    for row_idx, c in enumerate(candidates, start=2):
        row_fill = alt_fill if row_idx % 2 == 0 else None
        applied_date = c.created_at.strftime("%d %b %Y") if c.created_at else ""
        exp_ctc = float(c.expected_ctc) if c.expected_ctc else ""
        years_exp = float(c.years_experience) if c.years_experience else ""

        row_data = [
            c.candidate_code,
            c.full_name,
            c.department_applied or "",
            c.status,
            c.qualification or "",
            years_exp,
            exp_ctc,
            applied_date,
        ]
        ws.row_dimensions[row_idx].height = 20
        for col_idx, value in enumerate(row_data, start=1):
            cell = ws.cell(row=row_idx, column=col_idx, value=value)
            cell.alignment = data_align
            cell.border = border
            if row_fill:
                cell.fill = row_fill

    # ── Freeze header ────────────────────────────────────────────────────────
    ws.freeze_panes = "A2"

    # Metadata sheet
    ws_meta = wb.create_sheet("Report Info")
    ws_meta["A1"] = "Generated by"
    ws_meta["B1"] = "Lupin Pre-Onboarding Connect"
    ws_meta["A2"] = "Generated at"
    ws_meta["B2"] = datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")
    ws_meta["A3"] = "Total candidates"
    ws_meta["B3"] = len(candidates)

    stream = io.BytesIO()
    wb.save(stream)
    stream.seek(0)

    timestamp = datetime.utcnow().strftime("%Y%m%d_%H%M")
    filename = f"lupin_candidates_{timestamp}.xlsx"

    logger.info("Excel export generated: %d candidates", len(candidates))

    return StreamingResponse(
        stream,
        media_type="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        headers={"Content-Disposition": f'attachment; filename="{filename}"'},
    )


# ---------------------------------------------------------------------------
# GET /reports/export/pdf
# ---------------------------------------------------------------------------

@router.get(
    "/export/pdf",
    summary="Export pipeline summary report as PDF (HR only)",
    response_class=StreamingResponse,
)
def export_pdf(
    db: Session = Depends(get_db),
    _: User = Depends(require_hr_role),
) -> StreamingResponse:
    from reportlab.lib import colors
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import cm
    from reportlab.platypus import (
        SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable,
    )

    totals = _get_funnel_totals(db)
    total_all = sum(v for k, v in totals.items() if k != "Joined")

    # Department breakdown
    dept_rows = (
        db.query(Candidate.department_applied, func.count(Candidate.id).label("count"))
        .filter(Candidate.department_applied.isnot(None))
        .group_by(Candidate.department_applied)
        .order_by(func.count(Candidate.id).desc())
        .all()
    )

    # Joined candidates for the report
    joined_list = (
        db.query(Candidate, JoiningRecord)
        .join(JoiningRecord, JoiningRecord.candidate_id == Candidate.id)
        .filter(JoiningRecord.status == JoiningStatus.joined.value)
        .order_by(JoiningRecord.joining_date.desc())
        .limit(10)
        .all()
    )

    stream = io.BytesIO()
    doc = SimpleDocTemplate(
        stream,
        pagesize=A4,
        rightMargin=2 * cm,
        leftMargin=2 * cm,
        topMargin=2 * cm,
        bottomMargin=2 * cm,
    )

    styles = getSampleStyleSheet()

    # Custom styles
    title_style = ParagraphStyle(
        "Title", parent=styles["Title"],
        fontSize=18, textColor=colors.HexColor("#0F2040"),
        spaceAfter=4,
    )
    subtitle_style = ParagraphStyle(
        "Subtitle", parent=styles["Normal"],
        fontSize=10, textColor=colors.HexColor("#6B96D6"),
        spaceAfter=2,
    )
    section_style = ParagraphStyle(
        "Section", parent=styles["Heading2"],
        fontSize=12, textColor=colors.HexColor("#0F2040"),
        spaceBefore=16, spaceAfter=6,
        borderPad=4,
    )
    note_style = ParagraphStyle(
        "Note", parent=styles["Normal"],
        fontSize=8, textColor=colors.HexColor("#888888"),
        spaceAfter=4,
    )

    DARK_BLUE = colors.HexColor("#0F2040")
    ACCENT = colors.HexColor("#14B8A6")
    LIGHT_BLUE = colors.HexColor("#EAF1FB")
    WHITE = colors.white

    story: List[Any] = []

    # ── Header ───────────────────────────────────────────────────────────────
    story.append(Paragraph("Lupin Pre-Onboarding Connect", title_style))
    story.append(Paragraph("Recruitment Pipeline — Summary Report", subtitle_style))
    story.append(Paragraph(
        f"Generated: {datetime.utcnow().strftime('%d %B %Y at %H:%M UTC')}",
        note_style,
    ))
    story.append(HRFlowable(width="100%", thickness=2, color=ACCENT, spaceAfter=12))

    # ── Stat summary strip ────────────────────────────────────────────────────
    stat_data = [
        ["Total Applications", "Active in Pipeline", "Joined", "Rejected / Hold"],
        [
            str(total_all),
            str(totals.get("New Application", 0) + totals.get("Shortlisted", 0) +
                totals.get("Interview Scheduled", 0) + totals.get("Selected", 0)),
            str(totals.get("Joined", 0)),
            str(totals.get("Rejected", 0) + totals.get("Hold", 0)),
        ],
    ]
    stat_table = Table(stat_data, colWidths=[4.25 * cm] * 4)
    stat_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), DARK_BLUE),
        ("TEXTCOLOR", (0, 0), (-1, 0), WHITE),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, 0), 9),
        ("ALIGN", (0, 0), (-1, -1), "CENTER"),
        ("BACKGROUND", (0, 1), (-1, 1), LIGHT_BLUE),
        ("FONTNAME", (0, 1), (-1, 1), "Helvetica-Bold"),
        ("FONTSIZE", (0, 1), (-1, 1), 18),
        ("TEXTCOLOR", (0, 1), (-1, 1), DARK_BLUE),
        ("ROWBACKGROUNDS", (0, 1), (-1, 1), [LIGHT_BLUE]),
        ("BOX", (0, 0), (-1, -1), 1, DARK_BLUE),
        ("INNERGRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#CCCCCC")),
        ("TOPPADDING", (0, 0), (-1, -1), 8),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
    ]))
    story.append(stat_table)
    story.append(Spacer(1, 0.5 * cm))

    # ── Funnel table ──────────────────────────────────────────────────────────
    story.append(Paragraph("Pipeline Funnel", section_style))

    funnel_header = [["Status", "Count", "% of Total"]]
    funnel_body = []
    for status_key in FUNNEL_ORDER:
        cnt = totals.get(status_key, 0)
        pct = f"{(cnt / total_all * 100):.1f}%" if total_all > 0 else "0.0%"
        funnel_body.append([status_key, str(cnt), pct])

    funnel_data = funnel_header + funnel_body
    funnel_table = Table(funnel_data, colWidths=[9 * cm, 4 * cm, 4 * cm])
    funnel_style = TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), DARK_BLUE),
        ("TEXTCOLOR", (0, 0), (-1, 0), WHITE),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 10),
        ("ALIGN", (1, 0), (-1, -1), "CENTER"),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [WHITE, LIGHT_BLUE]),
        ("BOX", (0, 0), (-1, -1), 1, DARK_BLUE),
        ("INNERGRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#CCCCCC")),
        ("TOPPADDING", (0, 0), (-1, -1), 7),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 7),
    ])
    funnel_table.setStyle(funnel_style)
    story.append(funnel_table)
    story.append(Spacer(1, 0.4 * cm))

    # ── Department breakdown ──────────────────────────────────────────────────
    story.append(Paragraph("Department Breakdown", section_style))

    dept_header = [["Department", "Candidates"]]
    dept_body = [[dept or "—", str(cnt)] for dept, cnt in dept_rows]
    dept_data = dept_header + dept_body
    dept_table = Table(dept_data, colWidths=[13 * cm, 4 * cm])
    dept_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), DARK_BLUE),
        ("TEXTCOLOR", (0, 0), (-1, 0), WHITE),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 10),
        ("ALIGN", (1, 0), (-1, -1), "CENTER"),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [WHITE, LIGHT_BLUE]),
        ("BOX", (0, 0), (-1, -1), 1, DARK_BLUE),
        ("INNERGRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#CCCCCC")),
        ("TOPPADDING", (0, 0), (-1, -1), 7),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 7),
    ]))
    story.append(dept_table)
    story.append(Spacer(1, 0.4 * cm))

    # ── Joined candidates ─────────────────────────────────────────────────────
    if joined_list:
        story.append(Paragraph("Confirmed Joinings", section_style))
        joined_header = [["Employee Code", "Name", "Department", "Designation", "Joining Date"]]
        joined_body = []
        for cand, jr in joined_list:
            joining_date_str = jr.joining_date.strftime("%d %b %Y") if jr.joining_date else "—"
            joined_body.append([
                jr.employee_code or "—",
                cand.full_name,
                jr.department or "—",
                jr.designation or "—",
                joining_date_str,
            ])
        joined_data = joined_header + joined_body
        joined_table = Table(joined_data, colWidths=[3.5 * cm, 4.5 * cm, 3.5 * cm, 3.5 * cm, 2 * cm])
        joined_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), DARK_BLUE),
            ("TEXTCOLOR", (0, 0), (-1, 0), WHITE),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, -1), 9),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [WHITE, LIGHT_BLUE]),
            ("BOX", (0, 0), (-1, -1), 1, DARK_BLUE),
            ("INNERGRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#CCCCCC")),
            ("TOPPADDING", (0, 0), (-1, -1), 6),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ]))
        story.append(joined_table)

    story.append(Spacer(1, 0.6 * cm))
    story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#CCCCCC")))
    story.append(Paragraph(
        "CONFIDENTIAL — For internal HR use only. This is a prototype system. "
        "Not connected to any live company system.",
        note_style,
    ))

    doc.build(story)
    stream.seek(0)

    timestamp = datetime.utcnow().strftime("%Y%m%d_%H%M")
    filename = f"lupin_pipeline_report_{timestamp}.pdf"

    logger.info("PDF report generated")

    return StreamingResponse(
        stream,
        media_type="application/pdf",
        headers={"Content-Disposition": f'attachment; filename="{filename}"'},
    )
